spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwtdb
    username: root
    password: admin123
    driver-class-nama: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true